services:
  movies_service:
    container_name: movies_service
    build: ./movies-service
    ports:
      - "50051:50051" 
    environment:
      - .env

    depends_on:
      - mongodb
    volumes: 
      - ./data:/app/data 

  mongodb:
    image: mongo:7.0
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

  api_gateway:
    container_name: api_gateway
    build:
      context: .
      dockerfile: ./api/Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - movies_service 

volumes:
  mongo-data: