services:
  mongodb:
    image: mongo:7.0
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    restart: unless-stopped

  rabbitmq:
    image: rabbitmq:3.13-management
    container_name: rabbitmq
    ports:
      - "5672:5672"     
      - "15672:15672"   
    environment:
      RABBITMQ_DEFAULT_USER: ${RABBITMQ_DEFAULT_USER:-user}
      RABBITMQ_DEFAULT_PASS: ${RABBITMQ_DEFAULT_PASS:-pass}
    restart: unless-stopped

  movies_service:
    image: movies-service:latest
    container_name: movies_service
    build:
      context: .
      dockerfile: ./movies-service/Dockerfile
    ports:
      - "50051:50051"
    env_file:
      - .env
    depends_on:
      - mongodb
      - rabbitmq
    restart: unless-stopped

  api_gateway:
    image: api-gateway:latest
    container_name: api_gateway
    build:
      context: .
      dockerfile: ./api/Dockerfile
    ports:
      - "8080:8080"
    env_file:
      - .env
    depends_on:
      - movies_service
      - rabbitmq
    restart: unless-stopped

volumes:
  mongo-data:
